### ISSUE TITLE
梅花易数跟搜索问题

### ISSUE THREAD

**Issue by rexinshimin0001** [Sakura7301/sakuraTools#2]
你好，我用了这个插件  梅花易数要是设为true 插件运行不了报错  说是要配置api 但是好像没有设置api的地方   然后搜索因为我还用了linkai  所以改了一下搜索的关键词   改成了查询  但是没发触发  或者搜一下  查一下 是有问题的  但如果用ai搜索 或者搜索是没问题的
![image](https://github.com/user-attachments/assets/aa32e834-a79d-4d5c-9c5f-bbe899ed057d)

**Comment by Sakura7301** [comment]
梅花易数的功能目前只对zhipuai做了适配，因为这个功能需要把起盘的结果发送给AI来获取解析，所以需要用到大模型。

zhipuai在默认并不会在config.json里面，你在config.py中可以找到这几个字段的介绍，如图。
![image](https://github.com/user-attachments/assets/e2409b72-421e-4e64-a01a-3f9f4ab7bdb0)

如果你想用linkai做同样的事情，那么可以参照 bot/linkai/link_ai_bot.py 文件中的实现对sakuraTools进行修改，修改位置如下图，有详细注释的。
![image](https://github.com/user-attachments/assets/333b7857-0f9a-42e6-8b69-b13af7a15f10)

![image](https://github.com/user-attachments/assets/83b108f1-9284-42df-9f14-dbd216ab1fd2)

**Comment by Sakura7301** [comment]
> 你好，我用了这个插件 梅花易数要是设为true 插件运行不了报错 说是要配置api 但是好像没有设置api的地方 然后搜索因为我还用了linkai 所以改了一下搜索的关键词 改成了查询 但是没发触发 或者搜一下 查一下 是有问题的 但如果用ai搜索 或者搜索是没问题的 ![image](https://private-user-images.githubusercontent.com/156735895/390619925-aa32e834-a79d-4d5c-9c5f-bbe899ed057d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzI5Njc3NDksIm5iZiI6MTczMjk2NzQ0OSwicGF0aCI6Ii8xNTY3MzU4OTUvMzkwNjE5OTI1LWFhMzJlODM0LWE3OWQtNGQ1Yy05YzVmLWJiZTg5OWVkMDU3ZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTMwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTEzMFQxMTUwNDlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01YjA3YzFmYjhmOGJhYjEwNWQ2ZTVjNDA0YmE0YjM5NjdlNDY2MjFlNzQ4ODMwZmQyMDA2M2YyZDZjNDJjN2NjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.OewAlZ71DOX80ORcXxn_GvWcIDlxrwRWcfS5BmfVshI)

现已去除梅花易数对zhipuAI的依赖，现在任意AI都可以进行梅花易数卜卦，你可以试试看
